### PR TITLE
PLAT-69308: Update user selection popup per UX

### PR DESCRIPTION
**Pull request by ryanjduffy**
image

## Resolution
* Refactored `UserSelectionAvatar` out of `WelcomePopup` into new app component
* Updated `UserSelectionPopup` to be a fullscreen popup using the newly refactored avatars
* Added temporary CSS variable overrides to `WelcomePopup` to force new theme styling until theme is ready

### CODE REVIEW

**Comment by Djspaceg** [comment]
I don't think we want UserSelectionPopup to be a fullscreen popup because the point of it was to show that we can live-switch users and themes without needing to cover/hide the whole screen.

**Comment by ryanjduffy** [comment]
To fulfill that same intent, we'll also need to implement a selection capability as we currently have with `SwitchItem`. The design, as I understand it, assumes that selecting an avatar will activate that profile and close the popup. If that's the case, there's not a lot of added value for a partial screen popup since it will immediately disappear on selection revealing the new theme.

@Djspaceg How would you like to proceed?

**Comment by Djspaceg** [comment]
@ryanjduffy I would prefer to discuss this with UX so we're all on the same page and designing for the same goal. I'm happy with merging the other two changes but would prefer to wait to merge the user selection popup changes.

**Comment by ryanjduffy** [comment]
Okay. I'll resolve the merge conflicts and pend it until then.

**Comment by Djspaceg** [comment]
You could just separate out the chunks of work and put the userselectionpopup into a new PR, so we can get the finished stuff right now.

**Comment by ryanjduffy** [comment]
There's not a lot of value in that. It was refactoring to support the given design which may not be useful under a new design. For example, if we don't use the avatar for user selection, it doesn't need to be refactored out.

**Comment by lishammel** [comment]
closing out - will use the solution in PLAT-71221 instead.

**Pull request closed without merging**
